---

- name: Gather the instance information for use in the instance swap
  include_tasks: get_instance_information.yml
  # provides rhel6_instance_... for details related to the donor

# We cannot loop over a block so we have to loop over a single include
- name: Migrate an instance
  include_tasks: migrate_instance.yml
  vars:
    donor_instance: '{{ instance_index }}'
  loop: '{{ donor_instances_info.instances }}'
  loop_control:
    loop_var: instance_index
