---
# If there is no private key file available for the ansible_host,
#   you need to remove any existing key

- name: Determine the presence of the temporary file
  ansible.builtin.stat:
    path: "{{ inject.private_key_path }}"
  register: temp_key_pem
  delegate_to: localhost
  delegate_facts: true
  run_once: true

- name: Determine if the temporary keys match.
  block:
  - name: evaluate | retrieve the sha1 hash from the file
    shell:
      cmd: "openssl pkcs8 -in {{ inject.private_key_path }} -nocrypt -topk8 -outform DER | openssl sha1 -c | cut -d' ' -f2"
    delegate_to: localhost
    delegate_facts: true
    run_once: true
    register: tmp_private_key_md5
    when: temp_key_pem.stat.exists
    
  - name: gather details for the key pair for temporary review
    amazon.aws.ec2_key:
      aws_access_key: "{{ inject.aws_access_key | default(omit) }}"
      aws_secret_key: "{{ inject.aws_secret_key | default(omit) }}"
      profile: "{{ inject.profile | default(omit) }}"
      region:  "{{ inject.region | default(omit) }}"
      name: rhel-6-els-temp-key
      wait: yes
      force: False
    delegate_to: localhost
    delegate_facts: true
    run_once: true
    register: rhel_6_els_temp_key
    when: temp_key_pem.stat.exists

  - name: report the key from the command line
    debug:
      var: tmp_private_key_md5.stdout
    when: tmp_private_key_md5 is defined

  - name: report the key from ec2 key
    debug:
      var: rhel_6_els_temp_key.key.fingerprint
    when: rhel_6_els_temp_key is defined

  - name: If the keys match, define keys_match as true
    set_fact:
      keys_match: true
    when: rhel_6_els_temp_key.key.fingerprint == tmp_private_key_md5.stdout
  always:        
  - name: create a new key pair for temporary use with the builder instance
    amazon.aws.ec2_key:
      aws_access_key: "{{ inject.aws_access_key | default(omit) }}"
      aws_secret_key: "{{ inject.aws_secret_key | default(omit) }}"
      profile: "{{ inject.profile | default(omit) }}"
      region:  "{{ inject.region | default(omit) }}"
      name: rhel-6-els-temp-key
      wait: yes
      force: True
      state: absent
    delegate_to: localhost
    delegate_facts: true
    when: keys_match is not defined
    run_once: true
    register: rhel_6_els_temp_key
  - name: create a new key pair for temporary use with the builder instance
    amazon.aws.ec2_key:
      aws_access_key: "{{ inject.aws_access_key | default(omit) }}"
      aws_secret_key: "{{ inject.aws_secret_key | default(omit) }}"
      profile: "{{ inject.profile | default(omit) }}"
      region:  "{{ inject.region | default(omit) }}"
      name: rhel-6-els-temp-key
      wait: yes
      force: True
      state: present
    delegate_to: localhost
    delegate_facts: true
    when: keys_match is not defined
    run_once: true
    register: rhel_6_els_temp_key
    notify:
      - save the private key to tmp for later use
